config/routes.rb
Rails.application.routes.draw do
  resources :words

  root 'welcome#index'
  get '/index', to: 'welcome#index'
end

app/models/word.rb
class Word < ActiveRecord::Base
	validates :ord, presence: true
	validates :klasse, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@noun = Word.where(klasse: "noun").sample
  	@verb = Word.where(klasse: "verb").sample

  	respond_to do |format|
  		format.html
  		format.json {render json: { verb: @verb.ord, noun: @noun.ord}}

  	end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	def index
		@words = Word.all
	end

	def show
		@word = Word.find(params[:id])
	end

	def new
		@word = Word.new
	end

	def edit
		@word = Word.find(params[:id])
	end

	def create
	  @word = Word.new(word_params)
	 
	  if @word.save
	    redirect_to controller: 'welcome'
	  else
	    render 'new'
	  end
	end

	def update
		@word = Word.find(params[:id])

		if @word.update(word_params)
			redirect_to @word
		else
			render 'edit'
		end
	end

	def destroy
		@word = Word.find(params[:id])
		@word.destroy

		redirect_to words_path
	end
	 
	private
	  def word_params
	    params.require(:word).permit(:ord, :klasse)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Namegen3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Generate a username:</h1>
 

<div id='userNameBox'>Fill</div>
<br>
<input type="button" value="Generate new name" onclick="vedKlikk()">
<br>
<br>
<%= link_to 'Add a new word', new_word_path %>


<script>
  var userNameBox = document.getElementById('userNameBox');

  function craft(data){
    var randVerb = data.verb;
    var randNoun = data.noun;
    var temp = randNoun.substr(0,1).toUpperCase() + randNoun.substr(1,randNoun.length-1) + randVerb.substr(0,1).toUpperCase() + randVerb.substr(1,randVerb.length-1);
    
    if(randVerb.substr((randVerb.length)-1, 1) == "e"){
      temp = temp + "r";    
    }
    
    else{
      temp = temp + "er";
    }

    userNameBox.innerHTML = temp;
  }

  function vedKlikk(){
    $.getJSON( '/index', function(data) {
      craft(data);
    });
  }
  
    
  



  
  

  

</script>

app/views/words/_form.html.erb
<%= form_for @word do |f| %>
	<% if @word.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@word.errors.count, "error") %> prohibited
        this word from being saved:
      </h2>
      <ul>
        <% @word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <p>
    <%= f.label :ord %><br>
    <%= f.text_field :ord %>
  </p>
 
  <p>
  	<%= f.radio_button :klasse, "verb" %>
		<%= f.label :klasse, "Verb", :value => "verb" %>  	
		<%= f.radio_button :klasse, "noun" %>
  	<%= f.label :klasse, "Noun", :value => "noun" %> 
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/words/edit.html.erb
<h1>Edit word</h1>
 
<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing all words:</h1>
 
<table>
  <tr>
    <th>Word</th>
    <th>Type</th>
  </tr>
 
  <% @words.each do |w| %>
    <tr>
      <td><%= w.ord %></td>
      <td><%= w.klasse %></td>
      <td><%= link_to 'Show', word_path(w) %></td>
      <td><%= link_to 'Edit', edit_word_path(w) %></td>
      <td><%= link_to 'Destroy', word_path(w),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', controller: 'welcome' %>

app/views/words/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @word.ord %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @word.klasse %>
</p>